/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Stop {
    durationMins: bigint;
    stopType: StopType;
    mileMarker: number;
    location: string;
}
export interface RouteResult {
    durationMins: bigint;
    hosSchedule: Array<HosEntry>;
    restartUsed: boolean;
    violations: Array<string>;
    stops: Array<Stop>;
    distanceMiles: number;
}
export interface LogBlock {
    remark: string;
    startTime: bigint;
    duration: bigint;
}
export interface LogInput {
    totalMiles: number;
    cycleType?: CycleType;
    carrierName: string;
    priorCycleHoursUsed?: number;
    routeResult: RouteResult;
    driverName: string;
    startDate: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface HosEntry {
    startTime: bigint;
    status: DutyStatus;
    endTime: bigint;
}
export interface DailyLog {
    totalMiles: number;
    cycleType: CycleType;
    totalOnDutyLast7Days: number;
    date: string;
    gridRows: Array<LogGridRow>;
    carrierName: string;
    onDutyHoursToday: number;
    driverName: string;
    remarks: string;
    availableHoursTomorrow: number;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface LogGridRow {
    status: DutyStatus;
    blocks: Array<LogBlock>;
}
export interface RouteInput {
    cycleHoursUsed: number;
    cycleType?: CycleType;
    pickupLat: number;
    pickupLon: number;
    dropoffLat: number;
    dropoffLon: number;
    currentLat: number;
    currentLon: number;
    useRestartIfNeeded?: boolean;
}
export enum CycleType {
    sixtyHourSevenDay = "sixtyHourSevenDay",
    seventyHourEightDay = "seventyHourEightDay"
}
export enum DutyStatus {
    onDutyNotDriving = "onDutyNotDriving",
    sleeperBerth = "sleeperBerth",
    driving = "driving",
    offDuty = "offDuty"
}
export enum StopType {
    dropoff = "dropoff",
    tenHourReset = "tenHourReset",
    pickup = "pickup",
    fuelStop = "fuelStop",
    restBreak = "restBreak"
}
export interface backendInterface {
    calculateRoute(input: RouteInput): Promise<RouteResult>;
    generateLogs(input: LogInput): Promise<Array<DailyLog>>;
    geocode(searchText: string): Promise<string>;
    transformGeocodeResponse(input: TransformationInput): Promise<TransformationOutput>;
}
import type { CycleType as _CycleType, DailyLog as _DailyLog, DutyStatus as _DutyStatus, HosEntry as _HosEntry, LogBlock as _LogBlock, LogGridRow as _LogGridRow, LogInput as _LogInput, RouteInput as _RouteInput, RouteResult as _RouteResult, Stop as _Stop, StopType as _StopType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async calculateRoute(arg0: RouteInput): Promise<RouteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateRoute(to_candid_RouteInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RouteResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateRoute(to_candid_RouteInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RouteResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateLogs(arg0: LogInput): Promise<Array<DailyLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateLogs(to_candid_LogInput_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateLogs(to_candid_LogInput_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async geocode(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.geocode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.geocode(arg0);
            return result;
        }
    }
    async transformGeocodeResponse(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformGeocodeResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformGeocodeResponse(arg0);
            return result;
        }
    }
}
function from_candid_CycleType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CycleType): CycleType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_DailyLog_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyLog): DailyLog {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_DutyStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DutyStatus): DutyStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_HosEntry_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HosEntry): HosEntry {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_LogGridRow_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LogGridRow): LogGridRow {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_RouteResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RouteResult): RouteResult {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_StopType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StopType): StopType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Stop_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stop): Stop {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationMins: bigint;
    stopType: _StopType;
    mileMarker: number;
    location: string;
}): {
    durationMins: bigint;
    stopType: StopType;
    mileMarker: number;
    location: string;
} {
    return {
        durationMins: value.durationMins,
        stopType: from_candid_StopType_n15(_uploadFile, _downloadFile, value.stopType),
        mileMarker: value.mileMarker,
        location: value.location
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalMiles: number;
    cycleType: _CycleType;
    totalOnDutyLast7Days: number;
    date: string;
    gridRows: Array<_LogGridRow>;
    carrierName: string;
    onDutyHoursToday: number;
    driverName: string;
    remarks: string;
    availableHoursTomorrow: number;
}): {
    totalMiles: number;
    cycleType: CycleType;
    totalOnDutyLast7Days: number;
    date: string;
    gridRows: Array<LogGridRow>;
    carrierName: string;
    onDutyHoursToday: number;
    driverName: string;
    remarks: string;
    availableHoursTomorrow: number;
} {
    return {
        totalMiles: value.totalMiles,
        cycleType: from_candid_CycleType_n34(_uploadFile, _downloadFile, value.cycleType),
        totalOnDutyLast7Days: value.totalOnDutyLast7Days,
        date: value.date,
        gridRows: from_candid_vec_n36(_uploadFile, _downloadFile, value.gridRows),
        carrierName: value.carrierName,
        onDutyHoursToday: value.onDutyHoursToday,
        driverName: value.driverName,
        remarks: value.remarks,
        availableHoursTomorrow: value.availableHoursTomorrow
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _DutyStatus;
    blocks: Array<_LogBlock>;
}): {
    status: DutyStatus;
    blocks: Array<LogBlock>;
} {
    return {
        status: from_candid_DutyStatus_n10(_uploadFile, _downloadFile, value.status),
        blocks: value.blocks
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationMins: bigint;
    hosSchedule: Array<_HosEntry>;
    restartUsed: boolean;
    violations: Array<string>;
    stops: Array<_Stop>;
    distanceMiles: number;
}): {
    durationMins: bigint;
    hosSchedule: Array<HosEntry>;
    restartUsed: boolean;
    violations: Array<string>;
    stops: Array<Stop>;
    distanceMiles: number;
} {
    return {
        durationMins: value.durationMins,
        hosSchedule: from_candid_vec_n7(_uploadFile, _downloadFile, value.hosSchedule),
        restartUsed: value.restartUsed,
        violations: value.violations,
        stops: from_candid_vec_n12(_uploadFile, _downloadFile, value.stops),
        distanceMiles: value.distanceMiles
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    status: _DutyStatus;
    endTime: bigint;
}): {
    startTime: bigint;
    status: DutyStatus;
    endTime: bigint;
} {
    return {
        startTime: value.startTime,
        status: from_candid_DutyStatus_n10(_uploadFile, _downloadFile, value.status),
        endTime: value.endTime
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onDutyNotDriving: null;
} | {
    sleeperBerth: null;
} | {
    driving: null;
} | {
    offDuty: null;
}): DutyStatus {
    return "onDutyNotDriving" in value ? DutyStatus.onDutyNotDriving : "sleeperBerth" in value ? DutyStatus.sleeperBerth : "driving" in value ? DutyStatus.driving : "offDuty" in value ? DutyStatus.offDuty : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dropoff: null;
} | {
    tenHourReset: null;
} | {
    pickup: null;
} | {
    fuelStop: null;
} | {
    restBreak: null;
}): StopType {
    return "dropoff" in value ? StopType.dropoff : "tenHourReset" in value ? StopType.tenHourReset : "pickup" in value ? StopType.pickup : "fuelStop" in value ? StopType.fuelStop : "restBreak" in value ? StopType.restBreak : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sixtyHourSevenDay: null;
} | {
    seventyHourEightDay: null;
}): CycleType {
    return "sixtyHourSevenDay" in value ? CycleType.sixtyHourSevenDay : "seventyHourEightDay" in value ? CycleType.seventyHourEightDay : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Stop>): Array<Stop> {
    return value.map((x)=>from_candid_Stop_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyLog>): Array<DailyLog> {
    return value.map((x)=>from_candid_DailyLog_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LogGridRow>): Array<LogGridRow> {
    return value.map((x)=>from_candid_LogGridRow_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HosEntry>): Array<HosEntry> {
    return value.map((x)=>from_candid_HosEntry_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CycleType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CycleType): _CycleType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_DutyStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DutyStatus): _DutyStatus {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_HosEntry_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HosEntry): _HosEntry {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_LogInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogInput): _LogInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_RouteInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RouteInput): _RouteInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_RouteResult_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RouteResult): _RouteResult {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_StopType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StopType): _StopType {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Stop_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stop): _Stop {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalMiles: number;
    cycleType?: CycleType;
    carrierName: string;
    priorCycleHoursUsed?: number;
    routeResult: RouteResult;
    driverName: string;
    startDate: string;
}): {
    totalMiles: number;
    cycleType: [] | [_CycleType];
    carrierName: string;
    priorCycleHoursUsed: [] | [number];
    routeResult: _RouteResult;
    driverName: string;
    startDate: string;
} {
    return {
        totalMiles: value.totalMiles,
        cycleType: value.cycleType ? candid_some(to_candid_CycleType_n3(_uploadFile, _downloadFile, value.cycleType)) : candid_none(),
        carrierName: value.carrierName,
        priorCycleHoursUsed: value.priorCycleHoursUsed ? candid_some(value.priorCycleHoursUsed) : candid_none(),
        routeResult: to_candid_RouteResult_n19(_uploadFile, _downloadFile, value.routeResult),
        driverName: value.driverName,
        startDate: value.startDate
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cycleHoursUsed: number;
    cycleType?: CycleType;
    pickupLat: number;
    pickupLon: number;
    dropoffLat: number;
    dropoffLon: number;
    currentLat: number;
    currentLon: number;
    useRestartIfNeeded?: boolean;
}): {
    cycleHoursUsed: number;
    cycleType: [] | [_CycleType];
    pickupLat: number;
    pickupLon: number;
    dropoffLat: number;
    dropoffLon: number;
    currentLat: number;
    currentLon: number;
    useRestartIfNeeded: [] | [boolean];
} {
    return {
        cycleHoursUsed: value.cycleHoursUsed,
        cycleType: value.cycleType ? candid_some(to_candid_CycleType_n3(_uploadFile, _downloadFile, value.cycleType)) : candid_none(),
        pickupLat: value.pickupLat,
        pickupLon: value.pickupLon,
        dropoffLat: value.dropoffLat,
        dropoffLon: value.dropoffLon,
        currentLat: value.currentLat,
        currentLon: value.currentLon,
        useRestartIfNeeded: value.useRestartIfNeeded ? candid_some(value.useRestartIfNeeded) : candid_none()
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationMins: bigint;
    hosSchedule: Array<HosEntry>;
    restartUsed: boolean;
    violations: Array<string>;
    stops: Array<Stop>;
    distanceMiles: number;
}): {
    durationMins: bigint;
    hosSchedule: Array<_HosEntry>;
    restartUsed: boolean;
    violations: Array<string>;
    stops: Array<_Stop>;
    distanceMiles: number;
} {
    return {
        durationMins: value.durationMins,
        hosSchedule: to_candid_vec_n21(_uploadFile, _downloadFile, value.hosSchedule),
        restartUsed: value.restartUsed,
        violations: value.violations,
        stops: to_candid_vec_n26(_uploadFile, _downloadFile, value.stops),
        distanceMiles: value.distanceMiles
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    status: DutyStatus;
    endTime: bigint;
}): {
    startTime: bigint;
    status: _DutyStatus;
    endTime: bigint;
} {
    return {
        startTime: value.startTime,
        status: to_candid_DutyStatus_n24(_uploadFile, _downloadFile, value.status),
        endTime: value.endTime
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationMins: bigint;
    stopType: StopType;
    mileMarker: number;
    location: string;
}): {
    durationMins: bigint;
    stopType: _StopType;
    mileMarker: number;
    location: string;
} {
    return {
        durationMins: value.durationMins,
        stopType: to_candid_StopType_n29(_uploadFile, _downloadFile, value.stopType),
        mileMarker: value.mileMarker,
        location: value.location
    };
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DutyStatus): {
    onDutyNotDriving: null;
} | {
    sleeperBerth: null;
} | {
    driving: null;
} | {
    offDuty: null;
} {
    return value == DutyStatus.onDutyNotDriving ? {
        onDutyNotDriving: null
    } : value == DutyStatus.sleeperBerth ? {
        sleeperBerth: null
    } : value == DutyStatus.driving ? {
        driving: null
    } : value == DutyStatus.offDuty ? {
        offDuty: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StopType): {
    dropoff: null;
} | {
    tenHourReset: null;
} | {
    pickup: null;
} | {
    fuelStop: null;
} | {
    restBreak: null;
} {
    return value == StopType.dropoff ? {
        dropoff: null
    } : value == StopType.tenHourReset ? {
        tenHourReset: null
    } : value == StopType.pickup ? {
        pickup: null
    } : value == StopType.fuelStop ? {
        fuelStop: null
    } : value == StopType.restBreak ? {
        restBreak: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CycleType): {
    sixtyHourSevenDay: null;
} | {
    seventyHourEightDay: null;
} {
    return value == CycleType.sixtyHourSevenDay ? {
        sixtyHourSevenDay: null
    } : value == CycleType.seventyHourEightDay ? {
        seventyHourEightDay: null
    } : value;
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<HosEntry>): Array<_HosEntry> {
    return value.map((x)=>to_candid_HosEntry_n22(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Stop>): Array<_Stop> {
    return value.map((x)=>to_candid_Stop_n27(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
